/**
 * database.types.ts
 *
 * Generated by: supabase gen types typescript --project-id <id> > types/database.types.ts
 *
 * DO NOT EDIT MANUALLY.
 * Regenerate after every schema migration:
 *   npx supabase gen types typescript --local > types/database.types.ts
 *
 * This file is a placeholder. Run the command above after `supabase start`
 * to populate it with the actual generated types from the local schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          phone: string | null;
          address: string | null;
          dentist_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone?: string | null;
          address?: string | null;
          dentist_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string | null;
          address?: string | null;
          dentist_name?: string | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          clinic_id: string;
          full_name: string;
          role: "dentist" | "receptionist" | "patient";
          signature_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          clinic_id: string;
          full_name: string;
          role: "dentist" | "receptionist" | "patient";
          signature_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          full_name?: string;
          role?: "dentist" | "receptionist" | "patient";
          signature_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          clinic_id: string;
          name: string;
          phone: string | null;
          date_of_birth: string | null;
          gender: "male" | "female" | "other" | null;
          address: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          notes: string | null;
          total_visits: number;
          last_visit: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          is_self_registered: boolean;
          portal_registered_at: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          name: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          total_visits?: number;
          last_visit?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          is_self_registered?: boolean;
          portal_registered_at?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          name?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          total_visits?: number;
          last_visit?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          is_self_registered?: boolean;
          portal_registered_at?: string | null;
        };
      };
      appointments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          dentist_id: string;
          scheduled_at: string;
          duration_minutes: number;
          source: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes: string | null;
          chief_complaints: string | null;
          medical_history: Json | null;
          oral_findings: string | null;
          provisional_diagnosis: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          dentist_id: string;
          scheduled_at: string;
          duration_minutes?: number;
          source: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status?: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes?: string | null;
          chief_complaints?: string | null;
          medical_history?: Json | null;
          oral_findings?: string | null;
          provisional_diagnosis?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          dentist_id?: string;
          scheduled_at?: string;
          duration_minutes?: number;
          source?: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status?: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes?: string | null;
          chief_complaints?: string | null;
          medical_history?: Json | null;
          oral_findings?: string | null;
          provisional_diagnosis?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      appointment_history: {
        Row: {
          id: string;
          appointment_id: string;
          action: "created" | "rescheduled" | "cancelled" | "status_changed";
          old_value: Json | null;
          new_value: Json | null;
          performed_by: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          appointment_id: string;
          action: "created" | "rescheduled" | "cancelled" | "status_changed";
          old_value?: Json | null;
          new_value?: Json | null;
          performed_by?: string | null;
          timestamp?: string;
        };
        // append-only: no fields may be updated via the client
        Update: {
          id?: never;
          appointment_id?: never;
          action?: never;
          old_value?: never;
          new_value?: never;
          performed_by?: never;
          timestamp?: never;
        };
      };
      queue_entries: {
        Row: {
          id: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          position: number;
          status: "waiting" | "in_progress" | "completed";
          checked_in_at: string;
          called_at: string | null;
          queue_date: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          position: number;
          status?: "waiting" | "in_progress" | "completed";
          checked_in_at?: string;
          called_at?: string | null;
          queue_date?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          appointment_id?: string;
          patient_id?: string;
          position?: number;
          status?: "waiting" | "in_progress" | "completed";
          checked_in_at?: string;
          called_at?: string | null;
          queue_date?: string;
        };
      };
      treatments: {
        Row: {
          id: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          treatment_type: string;
          internal_notes: string | null;
          patient_visible_notes: string | null;
          cost: number;
          status: "planned" | "in_progress" | "completed" | "cancelled" | "declined";
          performed_at: string | null;
          medications: Json;
          opd_charged: boolean;
          xray_taken: boolean;
          xray_cost: number | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          consultant_id: string | null;
          commission_type: "percentage" | "fixed" | null;
          commission_value: number | null;
          consultant_share: number | null;
          clinic_share: number | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          treatment_type: string;
          internal_notes?: string | null;
          patient_visible_notes?: string | null;
          cost?: number;
          status?: "planned" | "in_progress" | "completed" | "cancelled" | "declined";
          performed_at?: string | null;
          medications?: Json;
          opd_charged?: boolean;
          xray_taken?: boolean;
          xray_cost?: number | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          consultant_id?: string | null;
          commission_type?: "percentage" | "fixed" | null;
          commission_value?: number | null;
          consultant_share?: number | null;
          clinic_share?: number | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          appointment_id?: string;
          patient_id?: string;
          treatment_type?: string;
          internal_notes?: string | null;
          patient_visible_notes?: string | null;
          cost?: number;
          status?: "planned" | "in_progress" | "completed" | "cancelled" | "declined";
          performed_at?: string | null;
          medications?: Json;
          opd_charged?: boolean;
          xray_taken?: boolean;
          xray_cost?: number | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          consultant_id?: string | null;
          commission_type?: "percentage" | "fixed" | null;
          commission_value?: number | null;
          consultant_share?: number | null;
          clinic_share?: number | null;
        };
      };
      treatment_documents: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          treatment_id: string | null;
          appointment_id: string | null;
          document_type: string | null;
          file_name: string;
          file_path: string;
          file_type: string;
          file_size: number | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          treatment_id?: string | null;
          appointment_id?: string | null;
          document_type?: string | null;
          file_name: string;
          file_path: string;
          file_type: string;
          file_size?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          treatment_id?: string | null;
          appointment_id?: string | null;
          document_type?: string | null;
          file_name?: string;
          file_path?: string;
          file_type?: string;
          file_size?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          appointment_id: string | null;
          treatment_id: string | null;
          amount: number;
          method: "cash" | "upi" | "card" | "bank_transfer";
          payment_type: "treatment" | "opd";
          payment_date: string;
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          amount: number;
          method: "cash" | "upi" | "card" | "bank_transfer";
          payment_type?: "treatment" | "opd";
          payment_date?: string;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          amount?: number;
          method?: "cash" | "upi" | "card" | "bank_transfer";
          payment_type?: "treatment" | "opd";
          payment_date?: string;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
      };
      follow_ups: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          appointment_id: string | null;
          treatment_id: string | null;
          follow_up_type: string;
          due_date: string;
          status: "pending" | "completed" | "cancelled";
          confirmation_status: "tentative" | "confirmed";
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          follow_up_type?: string;
          due_date: string;
          status?: "pending" | "completed" | "cancelled";
          confirmation_status?: "tentative" | "confirmed";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          follow_up_type?: string;
          due_date?: string;
          status?: "pending" | "completed" | "cancelled";
          confirmation_status?: "tentative" | "confirmed";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      patient_portal_links: {
        Row: {
          id: string;
          patient_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          user_id: string;
          created_at?: string;
        };
        // immutable: no fields may be updated via the client
        Update: {
          id?: never;
          patient_id?: never;
          user_id?: never;
          created_at?: never;
        };
      };
      clinic_settings: {
        Row: {
          clinic_id: string;
          clinic_name: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          clinic_hours: Json | null;
          average_appointment_duration: number;
          timezone: string;
          registration_number: string | null;
          allow_receptionist_payments: boolean;
          show_consultancy_on_dashboard: boolean;
          default_opd_fee: number | null;
          enable_xray_charges: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          clinic_id: string;
          clinic_name: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          clinic_hours?: Json | null;
          average_appointment_duration?: number;
          timezone?: string;
          registration_number?: string | null;
          allow_receptionist_payments?: boolean;
          show_consultancy_on_dashboard?: boolean;
          default_opd_fee?: number | null;
          enable_xray_charges?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          clinic_id?: string;
          clinic_name?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          clinic_hours?: Json | null;
          average_appointment_duration?: number;
          timezone?: string;
          registration_number?: string | null;
          allow_receptionist_payments?: boolean;
          show_consultancy_on_dashboard?: boolean;
          default_opd_fee?: number | null;
          enable_xray_charges?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      availability_rules: {
        Row: {
          id: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          slot_duration_minutes: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          slot_duration_minutes?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
          slot_duration_minutes?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      consultants: {
        Row: {
          id: string;
          clinic_id: string;
          name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      consultancy_income: {
        Row: {
          id: string;
          clinic_id: string;
          dentist_id: string;
          date: string;
          external_clinic: string | null;
          description: string | null;
          amount: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          dentist_id: string;
          date: string;
          external_clinic?: string | null;
          description?: string | null;
          amount: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          dentist_id?: string;
          date?: string;
          external_clinic?: string | null;
          description?: string | null;
          amount?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      consultancy_schedules: {
        Row: {
          id: string;
          clinic_id: string;
          dentist_id: string | null;
          date: string;
          start_time: string;
          end_time: string;
          reason: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          dentist_id?: string | null;
          date: string;
          start_time: string;
          end_time: string;
          reason?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          dentist_id?: string | null;
          date?: string;
          start_time?: string;
          end_time?: string;
          reason?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      unavailable_dates: {
        Row: {
          id: string;
          clinic_id: string;
          dentist_id: string | null;
          date: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          dentist_id?: string | null;
          date: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          dentist_id?: string | null;
          date?: string;
          reason?: string | null;
          created_at?: string;
        };
      };
      webhook_logs: {
        Row: {
          id: string;
          clinic_id: string | null;
          event_type: string;
          payload: Json | null;
          received_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          event_type: string;
          payload?: Json | null;
          received_at?: string;
        };
        // append-only: no fields may be updated via the client
        Update: {
          id?: never;
          clinic_id?: never;
          event_type?: never;
          payload?: never;
          received_at?: never;
        };
      };
    };
    Views: {
      active_patients: {
        Row: Database["public"]["Tables"]["patients"]["Row"];
      };
      active_appointments: {
        Row: Database["public"]["Tables"]["appointments"]["Row"];
      };
      active_treatments: {
        Row: Database["public"]["Tables"]["treatments"]["Row"];
      };
      active_payments: {
        Row: Database["public"]["Tables"]["payments"]["Row"];
      };
      active_follow_ups: {
        Row: Database["public"]["Tables"]["follow_ups"]["Row"];
      };
      overdue_follow_ups: {
        Row: Database["public"]["Tables"]["follow_ups"]["Row"];
      };
    };
    Functions: {
      auth_clinic_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      auth_role: {
        Args: Record<string, never>;
        Returns: "dentist" | "receptionist" | "patient";
      };
      auth_patient_id: {
        Args: Record<string, never>;
        Returns: string | null;
      };
      create_patient_appointment: {
        Args: {
          p_patient_id: string;
          p_scheduled_at: string;
          p_notes?: string;
        };
        Returns: string;
      };
    };
    Enums: {
      user_role: "dentist" | "receptionist" | "patient";
      gender_type: "male" | "female" | "other";
      appointment_source: "walk_in" | "phone_call" | "website" | "referral" | "other";
      appointment_status: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
      queue_status: "waiting" | "in_progress" | "completed";
      treatment_status: "planned" | "in_progress" | "completed" | "cancelled" | "declined";
      payment_method: "cash" | "upi" | "card" | "bank_transfer";
      follow_up_status: "pending" | "completed" | "cancelled";
      appointment_history_action: "created" | "rescheduled" | "cancelled" | "status_changed";
      follow_up_confirmation_status: "tentative" | "confirmed";
    };
    /**
     * Required by @supabase/supabase-js: a schema without this key does not
     * satisfy its `GenericSchema` constraint, so every `.from(...)` collapses to
     * `never` and the client appears untyped. Its absence is why so much of the
     * codebase falls back to `type DbClient = any`.
     *
     * `supabase gen types` always emits this block; it was missed because this
     * file is hand-maintained. Empty is correct — the schema defines no
     * composite types.
     */
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
