/**
 * database.types.ts
 *
 * Generated by: supabase gen types typescript --project-id <id> > types/database.types.ts
 *
 * DO NOT EDIT MANUALLY.
 * Regenerate after every schema migration:
 *   npx supabase gen types typescript --local > types/database.types.ts
 *
 * This file is a placeholder. Run the command above after `supabase start`
 * to populate it with the actual generated types from the local schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          phone: string | null;
          address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          clinic_id: string;
          full_name: string;
          role: "dentist" | "receptionist" | "patient";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          clinic_id: string;
          full_name: string;
          role: "dentist" | "receptionist" | "patient";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          full_name?: string;
          role?: "dentist" | "receptionist" | "patient";
          created_at?: string;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          clinic_id: string;
          name: string;
          phone: string | null;
          date_of_birth: string | null;
          gender: "male" | "female" | "other" | null;
          address: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          notes: string | null;
          total_visits: number;
          last_visit: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          name: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          total_visits?: number;
          last_visit?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          name?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          total_visits?: number;
          last_visit?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      appointments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          dentist_id: string;
          scheduled_at: string;
          duration_minutes: number;
          source: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          dentist_id: string;
          scheduled_at: string;
          duration_minutes?: number;
          source: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status?: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          dentist_id?: string;
          scheduled_at?: string;
          duration_minutes?: number;
          source?: "walk_in" | "phone_call" | "website" | "referral" | "other";
          status?: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      appointment_history: {
        Row: {
          id: string;
          appointment_id: string;
          action: "created" | "rescheduled" | "cancelled" | "status_changed";
          old_value: Json | null;
          new_value: Json | null;
          performed_by: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          appointment_id: string;
          action: "created" | "rescheduled" | "cancelled" | "status_changed";
          old_value?: Json | null;
          new_value?: Json | null;
          performed_by?: string | null;
          timestamp?: string;
        };
        Update: Record<string, never>; // append-only
      };
      queue_entries: {
        Row: {
          id: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          position: number;
          status: "waiting" | "in_progress" | "completed";
          checked_in_at: string;
          called_at: string | null;
          queue_date: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          position: number;
          status?: "waiting" | "in_progress" | "completed";
          checked_in_at?: string;
          called_at?: string | null;
          queue_date?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          appointment_id?: string;
          patient_id?: string;
          position?: number;
          status?: "waiting" | "in_progress" | "completed";
          checked_in_at?: string;
          called_at?: string | null;
          queue_date?: string;
        };
      };
      treatments: {
        Row: {
          id: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          treatment_type: string;
          internal_notes: string | null;
          patient_visible_notes: string | null;
          cost: number;
          status: "planned" | "in_progress" | "completed" | "cancelled";
          performed_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          appointment_id: string;
          patient_id: string;
          treatment_type: string;
          internal_notes?: string | null;
          patient_visible_notes?: string | null;
          cost?: number;
          status?: "planned" | "in_progress" | "completed" | "cancelled";
          performed_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          appointment_id?: string;
          patient_id?: string;
          treatment_type?: string;
          internal_notes?: string | null;
          patient_visible_notes?: string | null;
          cost?: number;
          status?: "planned" | "in_progress" | "completed" | "cancelled";
          performed_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      payments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          appointment_id: string | null;
          amount: number;
          method: "cash" | "upi" | "card" | "bank_transfer";
          payment_date: string;
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          appointment_id?: string | null;
          amount: number;
          method: "cash" | "upi" | "card" | "bank_transfer";
          payment_date?: string;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          appointment_id?: string | null;
          amount?: number;
          method?: "cash" | "upi" | "card" | "bank_transfer";
          payment_date?: string;
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
      };
      follow_ups: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          appointment_id: string | null;
          treatment_id: string | null;
          due_date: string;
          status: "pending" | "completed" | "cancelled";
          notes: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          due_date: string;
          status?: "pending" | "completed" | "cancelled";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          appointment_id?: string | null;
          treatment_id?: string | null;
          due_date?: string;
          status?: "pending" | "completed" | "cancelled";
          notes?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      patient_portal_links: {
        Row: {
          id: string;
          patient_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: Record<string, never>; // immutable
      };
      clinic_settings: {
        Row: {
          clinic_id: string;
          clinic_name: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          clinic_hours: Json | null;
          average_appointment_duration: number;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          clinic_id: string;
          clinic_name: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          clinic_hours?: Json | null;
          average_appointment_duration?: number;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          clinic_id?: string;
          clinic_name?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          clinic_hours?: Json | null;
          average_appointment_duration?: number;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      availability_rules: {
        Row: {
          id: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          slot_duration_minutes: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          slot_duration_minutes?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
          slot_duration_minutes?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      webhook_logs: {
        Row: {
          id: string;
          clinic_id: string | null;
          event_type: string;
          payload: Json | null;
          received_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          event_type: string;
          payload?: Json | null;
          received_at?: string;
        };
        Update: Record<string, never>; // append-only
      };
    };
    Views: {
      active_patients: {
        Row: Database["public"]["Tables"]["patients"]["Row"];
      };
      active_appointments: {
        Row: Database["public"]["Tables"]["appointments"]["Row"];
      };
      active_treatments: {
        Row: Database["public"]["Tables"]["treatments"]["Row"];
      };
      active_payments: {
        Row: Database["public"]["Tables"]["payments"]["Row"];
      };
      active_follow_ups: {
        Row: Database["public"]["Tables"]["follow_ups"]["Row"];
      };
      overdue_follow_ups: {
        Row: Database["public"]["Tables"]["follow_ups"]["Row"];
      };
    };
    Functions: {
      auth_clinic_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      auth_role: {
        Args: Record<string, never>;
        Returns: "dentist" | "receptionist" | "patient";
      };
      auth_patient_id: {
        Args: Record<string, never>;
        Returns: string | null;
      };
      create_patient_appointment: {
        Args: {
          p_patient_id: string;
          p_scheduled_at: string;
          p_notes?: string;
        };
        Returns: string;
      };
    };
    Enums: {
      user_role: "dentist" | "receptionist" | "patient";
      gender_type: "male" | "female" | "other";
      appointment_source: "walk_in" | "phone_call" | "website" | "referral" | "other";
      appointment_status: "scheduled" | "checked_in" | "in_progress" | "completed" | "cancelled" | "no_show";
      queue_status: "waiting" | "in_progress" | "completed";
      treatment_status: "planned" | "in_progress" | "completed" | "cancelled";
      payment_method: "cash" | "upi" | "card" | "bank_transfer";
      follow_up_status: "pending" | "completed" | "cancelled";
      appointment_history_action: "created" | "rescheduled" | "cancelled" | "status_changed";
    };
  };
};
