/**
 * Metrics Engine — Capacity calculators
 *
 * Capacity is measured in CHAIR-MINUTES, not slot counts.
 *
 * The obvious implementation — count the bookable slots a clinic offers, count
 * the appointments in them, divide — is wrong twice over, and both errors run in
 * the same direction: they make a busy clinic look idle.
 *
 *   1. A "slot" is a candidate START TIME, generated by stepping through each
 *      availability rule at `slot_duration_minutes`. Those candidates OVERLAP.
 *      A four-hour window stepped every 10 minutes yields 24 of them, and you
 *      plainly cannot book 24 half-hour appointments in four hours. Counting
 *      them as capacity inflates the denominator by the ratio of appointment
 *      length to step size — and because clinics set different steps on
 *      different weekdays, the same clinic reads differently on a Monday than a
 *      Friday, which makes the metric inconsistent with itself.
 *
 *   2. Appointments are not all the same length. Production data runs from 10 to
 *      60 minutes. One appointment is one slot only if every appointment is
 *      exactly a slot long.
 *
 * Minutes have neither problem. Open minutes are the union of the clinic's rule
 * windows less any blocks; booked minutes are the sum of appointment durations;
 * the ratio is real utilization at any granularity, on any weekday.
 *
 * Spare capacity is still REPORTED in appointments, because "room for about 4
 * more" is what a dentist acts on and "180 minutes free" is not. That conversion
 * is presentation, using the clinic's own typical appointment length — it is not
 * how the utilization is computed.
 */

import type { Metric } from "../../../domain";
import type { ClinicDataSnapshot } from "../../../repositories";
import { MetricKey, buildMetric } from "../metric-ids";
import { bookedMinutes, fillRate } from "../support/windows";

/**
 * Total chair-minutes the clinic can deliver today: open time × chairs.
 *
 * The chair multiplier is what makes this correct for a practice with more than
 * one operatory. Three chairs genuinely deliver three appointments in the same
 * hour; treating that clinic as one chair reports it at 300% utilization, which
 * the cap then flattens to a permanent 100% — an ordinary day indistinguishable
 * from a genuinely overloaded one.
 */
function capacityMinutes(s: ClinicDataSnapshot): number {
  return Math.max(0, s.capacity.openMinutesToday) * Math.max(1, s.capacity.chairCount);
}

/** Typical appointment length, guarded so it can never be a zero divisor. */
function typicalMinutes(s: ClinicDataSnapshot): number {
  const value = s.capacity.typicalAppointmentMinutes;
  return value > 0 ? value : 30;
}

/**
 * Chair utilization (%) — booked chair-minutes as a share of open chair-minutes.
 *
 * WITHHELD (null) on a closed day — a day the clinic offered no chair time at
 * all. A utilization percentage against zero open minutes is undefined, and
 * reporting it as "0%" is actively misleading: it implies unused available
 * capacity on a day there was none, which then costs the clinic health-score
 * points for being shut. An OPEN day that simply booked nothing genuinely IS 0%
 * (real unused capacity) and is reported as 0, not withheld.
 *
 * Capped at 100%: double-booking is real, but "we are 130% booked" is a
 * scheduling error to fix, not a capacity reading, and letting it through would
 * let one mistake dominate the 30-day average.
 */
export function chairUtilization(s: ClinicDataSnapshot): Metric | null {
  const capacity = capacityMinutes(s);
  if (capacity <= 0) return null; // closed day: no capacity to measure against
  const raw = (bookedMinutes(s.appointmentsToday) / capacity) * 100;
  const value = Math.round(Math.min(100, raw) * 10) / 10;
  return buildMetric(MetricKey.CAPACITY_CHAIR_UTILIZATION, value, s.clinicId, s.date, s.asOf);
}

/**
 * How many more typical appointments still fit today.
 *
 * Floored at zero and rounded DOWN: half an appointment's worth of gap is not a
 * bookable appointment, and reporting room that does not exist is the one error
 * that would send a receptionist looking for a patient to fill it.
 */
export function availableSlotsToday(s: ClinicDataSnapshot): Metric {
  const free = capacityMinutes(s) - bookedMinutes(s.appointmentsToday);
  const value = Math.max(0, Math.floor(free / typicalMinutes(s)));
  return buildMetric(MetricKey.CAPACITY_AVAILABLE_SLOTS_TODAY, value, s.clinicId, s.date, s.asOf);
}

/**
 * Chair-minutes the clinic is open for today, before any booking.
 *
 * The denominator behind utilization, published as a fact in its own right so
 * the percentage above can be checked rather than taken on trust — and so a
 * closed day is visibly zero rather than silently absent.
 */
export function openMinutesToday(s: ClinicDataSnapshot): Metric {
  return buildMetric(
    MetricKey.CAPACITY_OPEN_MINUTES_TODAY,
    capacityMinutes(s),
    s.clinicId,
    s.date,
    s.asOf,
  );
}

/**
 * The same capacity expressed in whole appointments.
 *
 * Not a redundant restatement of open minutes: it is the unit every volume
 * judgement is actually made in. "Six appointments today" means nothing until
 * you know the clinic had room for eight or for thirty, and threshold
 * calibration needs that denominator in appointments to size a floor from it
 * (see signals/config/calibration.ts). Minutes cannot be converted downstream,
 * because the typical appointment length lives on the snapshot, not on a metric.
 */
export function appointmentCapacityToday(s: ClinicDataSnapshot): Metric {
  const value = Math.floor(capacityMinutes(s) / typicalMinutes(s));
  return buildMetric(
    MetricKey.CAPACITY_APPOINTMENT_CAPACITY_TODAY,
    value,
    s.clinicId,
    s.date,
    s.asOf,
  );
}

/**
 * Chair utilization averaged across the trailing window.
 *
 * Daily utilization swings wildly — a single cancellation moves it double
 * digits — so the daily figure is a poor basis for any decision. The 30-day
 * number is what tells an owner whether to hire, extend hours, or market.
 *
 * WITHHELD when the window is absent, or when the clinic offered no capacity at
 * all across it (a rate against zero open time is undefined).
 */
export function chairUtilization30d(s: ClinicDataSnapshot): Metric | null {
  const window = s.trailingWindow;
  if (window === undefined) return null;
  const value = fillRate(window);
  if (value === null) return null;
  return buildMetric(
    MetricKey.CAPACITY_CHAIR_UTILIZATION_30D,
    value,
    s.clinicId,
    s.date,
    s.asOf,
  );
}

/**
 * How full the schedule is for the days AHEAD — future schedule health.
 *
 * The only forward-looking metric the engine produces, and the only one that can
 * warn rather than diagnose. Every other metric reports what already happened,
 * by which time the week is lost; a thin week ahead can still be filled from the
 * recall list.
 *
 * WITHHELD when the forward window is absent, or when the clinic offers no
 * capacity in it — a clinic closed for the week is not 0% booked, it is not
 * open, and those must not read the same.
 */
export function bookedNext7d(s: ClinicDataSnapshot): Metric | null {
  const window = s.forwardWindow;
  if (window === undefined) return null;
  const value = fillRate(window);
  if (value === null) return null;
  return buildMetric(MetricKey.CAPACITY_BOOKED_NEXT_7D, value, s.clinicId, s.date, s.asOf);
}
