-- =============================================================================
-- DentGrow — RLS policy evaluation: per-row → per-query
-- Migration: 20260818000000_rls_initplan_optimization.sql
--
-- WHAT THIS CHANGES
--   Every policy predicate that called auth_clinic_id(), auth_role(),
--   auth_patient_id() or auth.uid() directly now calls it through a scalar
--   subselect — `(select auth_clinic_id())` instead of `auth_clinic_id()`.
--
-- WHY
--   Those helpers are `stable security definer` functions that each run
--   `select ... from profiles where id = auth.uid()`. Called bare inside an
--   RLS predicate, Postgres evaluates them ONCE PER ROW, so listing patients
--   meant thousands of profile lookups. Wrapping the call in a subselect makes
--   the planner hoist it into an InitPlan, evaluated ONCE PER QUERY.
--
--   It also makes the value a plan-time constant, so `clinic_id = (select
--   auth_clinic_id())` becomes usable as an INDEX CONDITION. Before, the
--   clinic predicate could not be pushed into an index scan at all.
--
-- MEASURED (local stack, 20k patients / 80k appointments / 40k treatments /
-- 30k payments / 15k follow-ups, EXPLAIN ANALYZE as the authenticated role):
--   patients list                654.4 ms → 9.3 ms   (~70x)
--   appointments, last 30 days   211.1 ms → 3.9 ms   (~54x)
--   revenue sum, last 90 days    225.8 ms → 3.1 ms   (~73x)
--   overdue follow-ups            81.8 ms → 2.9 ms   (~28x)
--
-- SECURITY
--   Access decisions are UNCHANGED. Each helper takes no arguments and reads
--   only session state, so `(select f())` returns exactly what `f()` returned;
--   only the number of evaluations differs. No policy is added, dropped, or
--   re-scoped, and no role's visibility changes — every USING/WITH CHECK
--   expression below is the existing predicate with the calls wrapped.
--
--   Statements are written out explicitly rather than generated by a DO block
--   so the full text of every security predicate is reviewable in the diff.
-- =============================================================================

alter policy "appointment_history: dentist read" on public.appointment_history using ((((select auth_role()) = 'dentist'::user_role) AND (EXISTS ( SELECT 1
   FROM appointments a
  WHERE ((a.id = appointment_history.appointment_id) AND (a.clinic_id = (select auth_clinic_id())))))));
alter policy "appointment_history: receptionist read" on public.appointment_history using ((((select auth_role()) = 'receptionist'::user_role) AND (EXISTS ( SELECT 1
   FROM appointments a
  WHERE ((a.id = appointment_history.appointment_id) AND (a.clinic_id = (select auth_clinic_id())))))));
alter policy "appointments: dentist delete" on public.appointments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "appointments: dentist insert" on public.appointments with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "appointments: dentist select" on public.appointments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "appointments: dentist update" on public.appointments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "appointments: portal read own" on public.appointments using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "appointments: portal update own" on public.appointments using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL) AND (status = ANY (ARRAY['scheduled'::appointment_status, 'checked_in'::appointment_status])))) with check (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "appointments: receptionist insert" on public.appointments with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "appointments: receptionist read" on public.appointments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "appointments: receptionist update" on public.appointments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "availability_rules: all staff read" on public.availability_rules using ((clinic_id = (select auth_clinic_id())));
alter policy "availability_rules: dentist delete" on public.availability_rules using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "availability_rules: dentist insert" on public.availability_rules with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "availability_rules: dentist update" on public.availability_rules using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "availability_rules: portal read" on public.availability_rules using (((clinic_id = ( SELECT patients.clinic_id
   FROM patients
  WHERE (patients.id = (select auth_patient_id())))) AND (is_active = true)));
alter policy "clinic_settings: all staff read" on public.clinic_settings using ((clinic_id = (select auth_clinic_id())));
alter policy "clinic_settings: dentist insert" on public.clinic_settings with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "clinic_settings: dentist update" on public.clinic_settings using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "clinic_settings: portal read" on public.clinic_settings using ((clinic_id = ( SELECT p.clinic_id
   FROM patients p
  WHERE (p.id = (select auth_patient_id())))));
alter policy "clinics: staff can read own clinic" on public.clinics using ((id = (select auth_clinic_id())));
alter policy "consent_audit: staff read" on public.consent_audit using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role]))));
alter policy "consent_template_versions: dentist insert" on public.consent_template_versions with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_template_versions: dentist select" on public.consent_template_versions using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_template_versions: receptionist select" on public.consent_template_versions using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "consent_templates: dentist delete" on public.consent_templates using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_templates: dentist insert" on public.consent_templates with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_templates: dentist select" on public.consent_templates using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_templates: dentist update" on public.consent_templates using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consent_templates: receptionist select" on public.consent_templates using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "consents: dentist delete" on public.consents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (status <> 'signed'::consent_status)));
alter policy "consents: dentist insert" on public.consents with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consents: dentist select" on public.consents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "consents: dentist update" on public.consents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL) AND (status <> 'signed'::consent_status))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consents: portal read own active" on public.consents using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL) AND (status <> 'cancelled'::consent_status)));
alter policy "consents: receptionist insert uploaded" on public.consents with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (source = 'uploaded'::consent_source)));
alter policy "consents: receptionist select" on public.consents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "consultancy_income: dentist full access" on public.consultancy_income using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consultancy_schedules: dentist write" on public.consultancy_schedules using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consultancy_schedules: portal read" on public.consultancy_schedules using (((clinic_id = ( SELECT patients.clinic_id
   FROM patients
  WHERE (patients.id = (select auth_patient_id())))) AND (is_active = true)));
alter policy "consultancy_schedules: staff read own clinic" on public.consultancy_schedules using ((clinic_id = (select auth_clinic_id())));
alter policy "consultants: dentist write" on public.consultants using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "consultants: staff read own clinic" on public.consultants using ((clinic_id = (select auth_clinic_id())));
alter policy "follow_ups: dentist delete" on public.follow_ups using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "follow_ups: dentist insert" on public.follow_ups with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "follow_ups: dentist select" on public.follow_ups using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "follow_ups: dentist update" on public.follow_ups using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "follow_ups: portal read own" on public.follow_ups using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "follow_ups: receptionist insert" on public.follow_ups with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "follow_ups: receptionist select" on public.follow_ups using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "follow_ups: receptionist update" on public.follow_ups using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "metric_history: dentist reads own clinic" on public.metric_history using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "portal_links: patient reads own link" on public.patient_portal_links using ((user_id = (select auth.uid())));
alter policy "patient_teeth: dentist delete" on public.patient_teeth using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "patient_teeth: dentist insert" on public.patient_teeth with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "patient_teeth: dentist select" on public.patient_teeth using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "patient_teeth: dentist update" on public.patient_teeth using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "patient_teeth: portal read own" on public.patient_teeth using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "patients: dentist delete" on public.patients using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "patients: dentist insert" on public.patients with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "patients: dentist select" on public.patients using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "patients: dentist update" on public.patients using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "patients: portal read own record" on public.patients using (((id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "patients: portal update own profile" on public.patients using (((id = (select auth_patient_id())) AND (deleted_at IS NULL))) with check (((id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "patients: receptionist insert" on public.patients with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "patients: receptionist read" on public.patients using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "patients: receptionist update" on public.patients using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "payments: dentist delete" on public.payments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "payments: dentist insert" on public.payments with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "payments: dentist select" on public.payments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "payments: dentist update" on public.payments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "payments: portal read own" on public.payments using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "payments: receptionist insert" on public.payments with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "payments: receptionist read" on public.payments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "payments: receptionist update" on public.payments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "profiles: read own clinic members" on public.profiles using ((clinic_id = (select auth_clinic_id())));
alter policy "profiles: update own profile" on public.profiles using ((id = (select auth.uid()))) with check (((id = (select auth.uid())) AND (clinic_id = (select auth_clinic_id())) AND (role = (select auth_role()))));
alter policy "queue_entries: dentist full access" on public.queue_entries using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "queue_entries: dentist read clinic" on public.queue_entries using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "queue_entries: patient read own entry" on public.queue_entries using ((patient_id = (select auth_patient_id())));
alter policy "queue_entries: portal read own" on public.queue_entries using ((patient_id = (select auth_patient_id())));
alter policy "queue_entries: receptionist full access" on public.queue_entries using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "queue_entries: receptionist read clinic" on public.queue_entries using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "queue_entries: staff insert" on public.queue_entries with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role]))));
alter policy "queue_entries: staff update" on public.queue_entries using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role]))));
alter policy "reminder_logs: dentist full access" on public.reminder_logs using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "reminder_logs: receptionist full access" on public.reminder_logs using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role)));
alter policy "tooth_history: dentist read" on public.tooth_history using ((EXISTS ( SELECT 1
   FROM patient_teeth pt
  WHERE ((pt.id = tooth_history.patient_tooth_id) AND (pt.clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)))));
alter policy "treatment_documents: dentist delete" on public.treatment_documents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "treatment_documents: dentist insert" on public.treatment_documents with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "treatment_documents: portal read own" on public.treatment_documents using ((patient_id = (select auth_patient_id())));
alter policy "treatment_documents: staff delete appointment docs" on public.treatment_documents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role])) AND (appointment_id IS NOT NULL)));
alter policy "treatment_documents: staff insert appointment docs" on public.treatment_documents with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role])) AND (appointment_id IS NOT NULL)));
alter policy "treatment_documents: staff read own clinic" on public.treatment_documents using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = ANY (ARRAY['dentist'::user_role, 'receptionist'::user_role]))));
alter policy "treatments: dentist delete" on public.treatments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "treatments: dentist insert" on public.treatments with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "treatments: dentist select" on public.treatments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL)));
alter policy "treatments: dentist update" on public.treatments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role) AND (deleted_at IS NULL))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "treatments: portal read own" on public.treatments using (((patient_id = (select auth_patient_id())) AND (deleted_at IS NULL)));
alter policy "treatments: receptionist read operational" on public.treatments using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'receptionist'::user_role) AND (deleted_at IS NULL)));
alter policy "unavailable_dates: dentist write" on public.unavailable_dates using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role))) with check (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
alter policy "unavailable_dates: portal read" on public.unavailable_dates using ((clinic_id = ( SELECT patients.clinic_id
   FROM patients
  WHERE (patients.id = (select auth_patient_id())))));
alter policy "unavailable_dates: staff read own clinic" on public.unavailable_dates using ((clinic_id = (select auth_clinic_id())));
alter policy "webhook_logs: dentist read" on public.webhook_logs using (((clinic_id = (select auth_clinic_id())) AND ((select auth_role()) = 'dentist'::user_role)));
